#!/usr/bin/env python3
"""Generate the publications include from structured JSON data."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "_publications.json"
OUTPUT_PATH = ROOT / "_publications.md"


def md_escape(value: str) -> str:
    """Escape only the Markdown characters that can break inline text."""
    return (
        value.replace("\\", "\\\\")
        .replace("[", "\\[")
        .replace("]", "\\]")
        .replace("*", "\\*")
        .replace("_", "\\_")
    )


def attr_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def format_authors(authors: list[str], bold_names: set[str]) -> str:
    formatted = []
    for author in authors:
        author_html = md_escape(author)
        if author in bold_names:
            author_html = f"**{author_html}**"
        formatted.append(author_html)

    if len(formatted) <= 1:
        return "".join(formatted)
    if len(formatted) == 2:
        return f"{formatted[0]} and {formatted[1]}"
    return f"{', '.join(formatted[:-1])}, and {formatted[-1]}"


def render_entry(index: int, entry: dict, bold_names: set[str]) -> list[str]:
    authors = format_authors(entry["authors"], bold_names)
    title = md_escape(entry["title"])
    url = attr_escape(entry["url"])
    venue = md_escape(entry["venue"])
    highlight = entry.get("highlight")

    suffix = f' <span class="publication-venue">{venue}</span>'
    if highlight:
        suffix += f" **({md_escape(highlight)})**"

    return [
        f"[{index}]",
        f': {authors}. [*{title}*]({url}){{target="_blank" .flj}}.{suffix}',
        "",
    ]


def render() -> str:
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    bold_names = set(data.get("bold_names", []))
    lines = [
        "<!-- Generated from _publications.json by scripts/render_publications.py. Do not edit this file directly. -->",
        "",
        f"## {data['title']}",
        "",
    ]

    for section in data["sections"]:
        lines.extend([f"### {section['heading']}", ""])
        if section.get("note"):
            lines.extend([f"<!-- {section['note']} -->", ""])
        lines.extend(["::: {.publication-list}", ""])
        for index, entry in enumerate(section["entries"], start=1):
            lines.extend(render_entry(index, entry, bold_names))
        lines.extend([":::", ""])

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    OUTPUT_PATH.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
